### ISSUE TITLE
多平台科学上网（Windows专辑） - BlOG BY SOLO

### ISSUE THREAD

**Issue by zhangziqi1999** [zhangziqi1999/blogcomments#6]
https://zhangziqi1999.github.io/2019/08/07/%E5%A4%9A%E5%B9%B3%E5%8F%B0%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91-Window%E4%B8%93%E8%BE%91/ 

 Every failure is leading towards success.

**Comment by BABYQC** [comment]
thanks for your share. it's  very useful.
